<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrendaSeeder extends Seeder
{
    public function run()
    {
        DB::table('prendas')->insert([
            // TORSO -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Mickey Mouse Blanca',
                'descripcion' => 'Camiseta básica de algodón color blanco, perfecta para el día a día.',
                'img_frontal' => 'frontalBlancaMickey.png',
                'img_trasera' => 'traseraBlancaMikey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa azul clara con estampados',
                'descripcion' => 'Camisa de lino azul clara, ideal para ocasiones semi-formales.',
                'img_frontal' => 'frontalVanGogh.png',
                'img_trasera' => 'traseraVanGogh.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera PSG',
                'descripcion' => 'Sudadera casual gris de manga larga y cuello redondo. Cuenta con logo de Paris Saint-Germain engomado en la parte delantera y estampado en la parte trasera, con detalle de parche en el bajo y un suave cepillado interior. Tiene acabado de canalé en cuello, puños y bajo de la prenda. Es de corte holgado.',
                'img_frontal' => 'frontalSudaderaPSG.png',
                'img_trasera' => 'traseraSudaderaPSG.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera negra PONY',
                'descripcion' => 'Sudadera de felpa de manga larga y cuello redondo. Cuenta con detalle de estampado de Pony x Lefties en la parte delantera, detalle de parche en el bajo y estampado de texto en la espalda. Tiene acabado de canalé en cuello, bajo y puños.',
                'img_frontal' => 'frontalSudaderaPONY.png',
                'img_trasera' => 'traseraSudaderaPONY.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera estampada capucha',
                'descripcion' => 'Sudadera carne de manga larga y cuello capucha con acabados en canale. Es de corte relajado. Cuenta con estampado en la parte delantera y suave cepillado interior. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaEstampadaCapucha.png',
                'img_trasera' => 'traseraSudaderaEstampadaCapucha.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera verde QUEENS',
                'descripcion' => 'Sudadera de manga larga y cuello redondo con acabados en canalé. Cuenta con estampado frontal delantero. Es de corte relajado y está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaQUEENS.png',
                'img_trasera' => 'traseraSudaderaQUEENS.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Le Studio',
                'descripcion' => 'Sudadera elegante estampada de manga larga y cuello capucha con acabado de canalé en puños y bajo. Es de corte relajado. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaLeStudio.png',
                'img_trasera' => 'traseraSudaderaLeStudio.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Villa Club',
                'descripcion' => 'Sudadera elegante de manga larga y cuello polo con cierre frontal de botones a tono. Cuenta con distintos bordados en la parte delantera de la prenda. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaVillaClub.png',
                'img_trasera' => 'traseraSudaderaVillaClub.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera bordada roja',
                'descripcion' => 'Sudadera de manga larga y cuello redondo. Tiene acabado de canalé en el bajo, puños y cuello. Cuenta con bordado de texto delantero. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaClubMember.png',
                'img_trasera' => 'traseraSudaderaClubMember.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Paris Saint-Germain Blanco',
                'descripcion' => 'Sudadera de manga larga y capucha con distintos estampados del equipo de fútbol Paris Saint-Germain, incluido uno en la capucha. Cuenta con detalle de parche en el brazo derecho. Tiene un suave cepillado interior. Es de corte ligeramente holgado.',
                'img_frontal' => 'frontalSudaderaPSGBlanco.png',
                'img_trasera' => 'traseraSudaderaPSGBlanco.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Paris Saint-Germain Negra',
                'descripcion' => 'Camiseta de manga corta y cuello redondo con estampados del equipo de fútbol Paris Saint-Germain por toda la prenda. Es de corte recto.',
                'img_frontal' => 'frontalCamisetaPSGNegra.png',
                'img_trasera' => 'traseraCamisetaPSGNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Jersey punto cremallera',
                'descripcion' => 'Jersey de manga larga y cuello subido con cierre de cremallera metálica en el pecho. Es de corte recto y está confeccionado en tejido de punto.',
                'img_frontal' => 'frontaljerseyNegroCremallero.png',
                'img_trasera' => 'traserajerseyNegroCremallero.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta print rosa',
                'descripcion' => 'Camiseta de rayas de algodón color rosa con dibujo en el pecho, perfecta para el día a día.',
                'img_frontal' => 'CamisetaMangaCortaPrintRosaFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaPrintRosaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa manga corta boxy',
                'descripcion' => 'Camisa manga corta boxy fit de rayas color azul de algodón, perfecta para el verano.',
                'img_frontal' => 'CamisaMangaCortaBoxyRayasFrontal.png',
                'img_trasera' => 'CamisaMangaCortaBoxyRayasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa manga corta boxy bordado',
                'descripcion' => 'Camisa manga corta boxy fit color azul marino de algodón con bordado en la parte trasera, perfecta para el verano.',
                'img_frontal' => 'CamisaMangaCortaBoxyBordadaFrontal.png',
                'img_trasera' => 'CamisaMangaCortaBoxyBordadaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Polo rayas',
                'descripcion' => 'Polo manga corta color azul con rayas negras y botones en el pecho, para ir formal pero cómodo.',
                'img_frontal' => 'PoloMangaCortaRayasFrontal.png',
                'img_trasera' => 'PoloMangaCortaRayasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa manga corta rota',
                'descripcion' => 'Camisa de color caqui (tono tierra suave) con mangas cortas y detalles deliberados de rotos o desgastes, dando un estilo casual y ligeramente desgastado. Ideal para looks informales con toque moderno.',
                'img_frontal' => 'CamisaMangaCortaRotaFrontal.png',
                'img_trasera' => 'CamisaMangaCortaRotaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa manga corta textura print',
                'descripcion' => 'Camisa con mangas cortas en tono arena (beige suave), con diseño de textura o estampado que imita la apariencia del suelo desértico o arenoso. Brinda un estilo natural, fresco y versátil, ideal para ocasiones casuales o informales.',
                'img_frontal' => 'CamisaMangaCortaTexturaPrintFrontal.png',
                'img_trasera' => 'CamisaMangaCortaTexturaPrintTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Cazadora técnica sport',
                'descripcion' => 'Chaqueta deportiva de corte moderno y funcional, en tono azul claro. Diseñada con materiales resistentes y cómodos, ideal para actividades al aire libre o para un estilo casual pero activo.',
                'img_frontal' => 'CazadoraTecnicaSportAzulFrontal.png',
                'img_trasera' => 'CazadoraTecnicaSportAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta rib contraste',
                'descripcion' => 'Camiseta de tiras anchas (rib) en colores blanco y rojo, con diseño de contraste entre ambos tonos. De manga corta y corte ajustado o entallado, ideal para un look retro, deportivo o casual con estilo definido.',
                'img_frontal' => 'CamisetaMangaCortaRibRojaFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaRibRojaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Cazadora rayas bordado',
                'descripcion' => 'Chaqueta con diseño de rayas en blanco y negro, decorada con detalles de bordado. Combina un estilo clásico y moderno, aportando un toque elegante y original. Ideal para looks casuales con personalidad.',
                'img_frontal' => 'CazadoraRayasBordadaFrontal.png',
                'img_trasera' => 'CazadoraRayasBordadaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Cazadora denim trucker',
                'descripcion' => 'Chaqueta tipo trucker fabricada en denim de color azul marino. Cuenta con bolsillos frontales característicos y cierre mediante botones, ofreciendo un estilo clásico y versátil. Ideal para looks casuales y combinaciones sencillas pero con actitud.',
                'img_frontal' => 'CazadoraDenimTruckerFrontal.png',
                'img_trasera' => 'CazadoraDenimTruckerTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Chaqueta Everlast cropped boxeo',
                'descripcion' => 'Chaqueta corta (cropped) de estilo deportivo, inspirada en la vestimenta de boxeo, de color gris y cierre con cremallera. Marca Everlast, conocida por su calidad en prendas de deporte. Ideal para looks urbanos, cómodos y con toque atlético.',
                'img_frontal' => 'ChaquetaEverlastCroppedBoxeoFrontal.png',
                'img_trasera' => 'ChaquetaEverlastCroppedBoxeoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta básica',
                'descripcion' => 'Prenda esencial de color negro, con mangas cortas y corte ajustado o regular. Versátil y sencilla, ideal para combinar en cualquier estilo, desde casual hasta más estilizado. Perfecta para usar sola o como base en capas.',
                'img_frontal' => 'CamisetaCortaBásicaNegraFrontal.png',
                'img_trasera' => 'CamisetaCortaBásicaNegraTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta mesh sport print',
                'descripcion' => 'Camiseta deportiva de color azul, con diseño en malla (mesh) para mayor transpirabilidad. Cuenta con un estampado frontal minimalista y en la parte trasera presenta números y letras blancos, típicos de uniformes atléticos o estilo retro deportivo. Ideal para looks activos, informales o con inspiración sport.',
                'img_frontal' => 'CamisetaMangaCortaMeshSportFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaMeshSportTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Nascar manga larga print',
                'descripcion' => 'Camiseta de manga larga con diseño inspirado en la temática NASCAR, en tono rosa. Cuenta con estampados característicos como logotipos, banderas o gráficos relacionados con el automovilismo. Ideal para quienes buscan un estilo casual con toque deportivo y colorido.',
                'img_frontal' => 'CamisetaNascarMangaLargaFrontal.png',
                'img_trasera' => 'CamisetaNascarMangaLargaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Polo manga corta sport mesh',
                'descripcion' => 'Polo de estilo deportivo confeccionado en tejido mesh para mayor transpiración. Presenta un diseño en blanco roto como color principal, con detalles en azul en el cuello y en los bordes de las mangas. Ideal para looks informales o deportivos, combinando comodidad, frescura y un toque moderno.',
                'img_frontal' => 'PoloMangaCortaMeshFrontal.png',
                'img_trasera' => 'PoloMangaCortaMeshTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Polo manga corta varsity parche',
                'descripcion' => 'Polo de corte deportivo inspirado en el estilo varsity (universitario), con manga corta y diseño color block. Presenta un parche rojo en el pecho, combinado con detalles de rayas negras y blancas en el cuerpo o mangas. Ideal para looks dinámicos y juveniles, aportando un toque retro y atlético al outfit.',
                'img_frontal' => 'PoloMangaCortaVarsityFrontal.png',
                'img_trasera' => 'PoloMangaCortaVarsityTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Everlast manga corta mesh',
                'descripcion' => 'Camiseta de la marca Everlast, con mangas cortas y confeccionada en tejido mesh transpirable. De color azul marino como base, incorpora rayas horizontales blancas que le dan un estilo deportivo y clásico. Ideal para looks activos o casuales, combinando comodidad, frescura y un toque atlético.',
                'img_frontal' => 'CamisetaEverlastMangaCortaFrontal.png',
                'img_trasera' => 'CamisetaEverlastMangaCortaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta rib contraste',
                'descripcion' => 'Camiseta de corte ajustado confeccionada en tejido rib (elástico y entrelazado), en combinación de tonos: azul claro y azul marino. Su diseño de contraste aporta dinamismo y estilo, ideal para looks informales o deportivos, combinando elegancia casual y comodidad.',
                'img_frontal' => 'CamisetaMangaCortaRibAzulFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaRibAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta print',
                'descripcion' => 'Camiseta de manga corta en tono suave tipo arena (beige claro), con estampado en contraste que puede incluir motivos geométricos, tribales o abstractos. Aporta un estilo fresco, natural y versátil, ideal para looks casuales o inspirados en tendencias bohemias o playeras.',
                'img_frontal' => 'CamisetaMangaCortaPrintFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaPrintTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta manga corta contraste print gris',
                'descripcion' => 'Camiseta de manga corta con diseño de estampado en tonos de gris, combinando diferentes intensidades o texturas del color para crear un efecto de contraste. Corte moderno y versátil, ideal para looks urbanos, informales o minimalistas, aportando estilo sencillo pero elegante.',
                'img_frontal' => 'CamisetaMangaCortaContrasteGrisFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaContrasteGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // PIERNA -----------------------------------------------------------------------------------------------

            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans Comfort Skinny Premium',
                'descripcion' => 'Pantalón azul vaquero básico de cinco bolsillos con cierre de botón metálico y cremallera. Su corte comfort skinny es ajustado y de tiro medio pero resulta muy cómodo gracias a la elasticidad de su tejido. El tejido, su elasticidad reforzada y la atención a sus detalles de diseño hacen de este modelo nuestro vaquero premium.',
                'img_frontal' => 'frontaljeansAzulesSkinny.png',
                'img_trasera' => 'traserajeansAzulesSkinny.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans jogger rotos negros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotos.png',
                'img_trasera' => 'traserajeansJoggerRotos.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans jogger rotos vaqueros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotosVaqueros.png',
                'img_trasera' => 'traserajeansJoggerRotosVaqueros.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón chándal Paris Saint-Germain',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Tiene distintos estampados del equipo de fútbol Paris Saint-Germain. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche. Tiene un suave cepillado interior.',
                'img_frontal' => 'frontalChandalPSGGris.png',
                'img_trasera' => 'traseraChandalPSGGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón chándal interlock',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger y cordón de ajuste a contraste. Cuenta con dos bolsillos laterales y uno trasero. Es de corte ligeramente ajustado. Está confeccionado en tejido de felpa con paneles con textura.',
                'img_frontal' => 'frontalChandalInterlockGris.png',
                'img_trasera' => 'traseraChandalInterlockGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda Paris Saint-Germain negra',
                'descripcion' => 'Bermuda de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con estampados engomados del equipo de fútbol Paris Saint-Germain. Tiene dos bolsillos laterales y un bolsillo trasero con detalle de parche. Está confeccionada en un tejido de felpa interlock.',
                'img_frontal' => 'frontalCortoPSGNegro.png',
                'img_trasera' => 'traseraCortoPSGNegro.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda elástica deportiva',
                'descripcion' => 'Bermuda azul oscuro deportiva con bolsillos de tejido técnico y detalles reflectantes en la parte trasera. Tiene cintura elástica con lazada delantera. Cuenta con un bolsillo oculto con cremallera junto al bolsillo derecho.',
                'img_frontal' => 'frontalBermudaDeportivaAzul.png',
                'img_trasera' => 'traseraBermudaDeportivaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim relaxed',
                'descripcion' => 'Bermuda denim relaxed',
                'img_frontal' => 'frontalBermudaNegra.png',
                'img_trasera' => 'traseraBermudaNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda jogger estructura Azul',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche.',
                'img_frontal' => 'frontalBermudaAzul.png',
                'img_trasera' => 'traseraBermudaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda jogger estructura Verde',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'frontalBermudaVerde.png',
                'img_trasera' => 'traseraBermudaVerde.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim skater',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoAzulFrontal.png',
                'img_trasera' => 'tejanoCortoAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans 90s straight negros',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoNegroFrontal.png',
                'img_trasera' => 'tejanoLargoNegrotrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy jacquard blancos',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoBlancoFrontal.png',
                'img_trasera' => 'tejanoLargoBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans super baggy azul fuerte',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulFuerteFrontal.png',
                'img_trasera' => 'tejanoLargoAzulFuerteTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón baggy técnico Verde',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalGrisVerdeFrontal.png',
                'img_trasera' => 'chandalGrisVerdeTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy azul',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulFrontal.png',
                'img_trasera' => 'tejanoLargoAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy print blanca y marron',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoBlancoMarronFrontal.png',
                'img_trasera' => 'tejanoLargoBlancoMarronTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy jacquard azul claro',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulEspecialFrontal.png',
                'img_trasera' => 'tejanoLargoAzulEspecialTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón técnico ribete sport',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalNegroFrontal.png',
                'img_trasera' => 'chandalNegroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón Volkswagen jacquard',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalVerdeBlancoFrontal.png',
                'img_trasera' => 'chandalVerdeBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans super baggy rotos',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoGrisFrontal.png',
                'img_trasera' => 'tejanoLargoGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim baggy gris',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoGrisFrontal.png',
                'img_trasera' => 'tejanoCortoGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda efecto neopreno oversize gris',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalCortoGrisFrontal.png',
                'img_trasera' => 'chandalCortoGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda baggy parches negra',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoNegroEspecialFrontal.png',
                'img_trasera' => 'tejanoCortoNegroEspecialTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim baggy flecos gris',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoGrisEspecialFrontal.png',
                'img_trasera' => 'tejanoCortoGrisEspecialTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda skater gris claro',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoGrisBlancoFrontal.png',
                'img_trasera' => 'tejanoCortoGrisBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda felpa print rosa',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalCortoAzulClaroFrontal.png',
                'img_trasera' => 'chandalCortoAzulClaroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda skater efecto deshilachado marron',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoMarronFrontal.png',
                'img_trasera' => 'tejanoCortoMarronTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda loose jogger con lino blanco',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalCortoBlancoFrontal.png',
                'img_trasera' => 'chandalCortoBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim baggy cargo print marron',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoMarronEstrellasFrontal.png',
                'img_trasera' => 'tejanoCortoMarronEstrellasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // CABEZA -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra Dragon Ball ©Bird Studio',
                'descripcion' => 'Gorra de visera curva con estampados de Dragon Ball ©Bird Studio en la parte delantera. Cuenta con rejilla en la parte trasera a contraste y cinta de ajuste adherente en la parte trasera.',
                'img_frontal' => 'frontalGorraDB.png',
                'img_trasera' => 'traseraGorraDB.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra Brooklyn Nets NBA Blanca y Negra',
                'descripcion' => 'Gorra de visera curva con cinta adherente en parte trasera para mejor ajuste. Cuenta con estampado a contraste de Brooklyn Nets NBA en parte delantera.',
                'img_frontal' => 'frontalGorraNBA.png',
                'img_trasera' => 'traseraGorraNBA.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas básicas efecto carey',
                'descripcion' => 'Gafas de sol de cristal redondo y montura de pasta acabada en efecto carey.',
                'img_frontal' => 'frontalGafasCarey.png',
                'img_trasera' => 'traseraGafasCarey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas rectangulares',
                'descripcion' => 'Gafas de sol de cristal rectangular con montura de pasta semitransparente.',
                'img_frontal' => 'frontalGafasRectangulares.png',
                'img_trasera' => 'traseraGafasRectangulares.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Pañuelo rojo',
                'descripcion' => 'Pañuelo con fondo de color rojo vibrante y estampado en contraste (puede ser en negro, blanco, dorado o tonos tierra), que incluye diseños como motivos florales, geométricos, étnicos o abstractos. Aporta un toque llamativo, elegante y lleno de energía al look. Ideal para usar en el cuello, cabello o como accesorio decorativo, combinando estilo y versatilidad.',
                'img_frontal' => 'PañueloRojoFrontal.png',
                'img_trasera' => 'PañueloRojoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Pañuelo negro',
                'descripcion' => 'Pañuelo de color base negro con estampado en tonos contrastantes (como blanco, gris, dorado o rojo), que puede incluir diseños geométricos, florales, étnicos o abstractos. Aporta un toque elegante, misterioso y versátil al outfit. Ideal para usar en el cuello, como complemento en el cabello o para personalizar bolsos y accesorios.',
                'img_frontal' => 'PañueloNegroFrontal.png',
                'img_trasera' => 'PañueloNegroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas sol polarizadas cristales azules',
                'descripcion' => 'Gafas de sol con lentes polarizados de color azul, que ayudan a reducir el deslumbramiento y mejorar el contraste visual. Las patillas (varillas) son de color negro, creando un contraste moderno y elegante. Diseñadas para ofrecer protección UV, comodidad y estilo, ideales tanto para actividades al aire libre como para complementar looks urbanos o deportivos.',
                'img_frontal' => 'GafasSolAzulesFrontal.png',
                'img_trasera' => 'GafasSolAzulesTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas sol leopardo',
                'descripcion' => 'Gafas de sol con diseño en tonos camel, marrón y negro en las patillas (varillas), imitando el clásico patrón leopardo . El resto de la montura puede ser neutra (negra, transparente o dorada), resaltando el detalle animal en las patillas. Este estilo aporta un toque salvaje, femenino y fashion al look. Ideal para quienes buscan un complemento llamativo y con personalidad, combinando elegancia y atrevimiento.',
                'img_frontal' => 'GafasSolLeopardoFrontal.png',
                'img_trasera' => 'GafasSolLeopardoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Pañuelo tie dye',
                'descripcion' => 'Pañuelo con técnica de teñido tie dye que combina suavemente los tonos crema, azul turquesa y negro en un diseño ondulado y orgánico. Ideal para agregar un toque bohemio, colorido y original a cualquier outfit. Versátil para usar en el cuello, cabello, bolsos o como accesorio decorativo.',
                'img_frontal' => 'PañueloTyeDyeFrontal.png',
                'img_trasera' => 'PañueloTyeDyeTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra bordado Crema',
                'descripcion' => 'Gorra con diseño de bordado en tonos crema y azul, que puede incluir logotipos, motivos decorativos o detalles geométricos. Combina elegancia casual con un toque de color, ideal para looks informales, deportivos o urbanos. Perfecta para usar a diario y complementar outfits con estilo sencillo pero cuidado.',
                'img_frontal' => 'GorraBordadaCremaFrontal.png',
                'img_trasera' => 'GorraBordadaCremaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra bordado blanco roto',
                'descripcion' => 'Gorra con detalles de bordado en tono blanco roto (blanco ligeramente apagado o marfil). Aporta un estilo limpio, sencillo y elegante, ideal para looks casuales o minimalistas. Perfecta para combinar con outfits claros o como contraste en estilos más neutros.',
                'img_frontal' => 'GorraBordadaCrema2Frontal.png',
                'img_trasera' => 'GorraBordadaCrema2Trasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Dock hat efecto lavado',
                'descripcion' => 'Sombrero tipo dock hat (de ala corta y copa baja) con acabado de efecto lavado en tono gris. Este estilo aporta un look vintage y desgastado, ideal para looks casuales, marineros o urbanos. Versátil y con toque retro, perfecto para complementar outfits informales con personalidad.',
                'img_frontal' => 'DockHatEfectoLavadoFrontal.png',
                'img_trasera' => 'DockHatEfectoLavadoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Bucket efecto lavado',
                'descripcion' => 'Sombrero tipo bucket (gorrito de lluvia) con acabado de efecto lavado en color crudo (beige muy claro o blanco sucio). Este estilo aporta un toque casual, ligeramente vintage y relajado. Ideal para looks informales, playeros o urbanos, combinando comodidad y estilo con un aire moderno y natural.',
                'img_frontal' => 'BucketEfectoLavadoFrontal.png',
                'img_trasera' => 'BucketEfectoLavadoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Bucket denim efecto lavado',
                'descripcion' => 'Sombrero tipo bucket (gorrito de lluvia) confeccionado en tela denim y acabado con efecto lavado, que le da un tono desgastado y aspecto vintage. Diseño casual y versátil, ideal para looks informales, retro o playeros. Perfecto para sumar estilo y comodidad a cualquier outfit urbano o al aire libre.',
                'img_frontal' => 'BucketDenimEfectoLavadoFrontal.png',
                'img_trasera' => 'BucketDenimEfectoLavadoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra bordado gris',
                'descripcion' => 'Gorra con diseño de bordado en combinación de colores negro y blanco, que puede incluir patrones geométricos, logotipos o detalles decorativos. Esta combinación aporta un estilo limpio, moderno y versátil, ideal para looks casuales, urbanos o deportivos. Perfecta para usar a diario con un toque de contraste y personalidad.',
                'img_frontal' => 'GorraBordadaGrisFrontal.png',
                'img_trasera' => 'GorraBordadaGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas sol polarizadas sport rosa',
                'descripcion' => 'Gafas deportivas con lentes polarizados de color rosa, que reducen el deslumbramiento y mejoran la claridad visual. Las patillas (varillas) son de color blanco, aportando un contraste moderno y fresco. Diseñadas para ofrecer comodidad y protección bajo el sol, ideales para actividades al aire libre o para un look casual con estilo sporty y toque fashion.',
                'img_frontal' => 'GafasSolRosaFrontal.png',
                'img_trasera' => 'GafasSolRosaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra acid',
                'descripcion' => 'Gorra con acabado acid wash en tono gris, que le da un efecto desgastado y moderno. Cuenta con detalles de llamas en color azul aplicados en los laterales, aportando un estilo urbano, rebelde y original. Ideal para looks casuales, streetwear o con toque grunge, combinando frescura, actitud y personalidad.',
                'img_frontal' => 'GorraLlamasAzulFrontal.png',
                'img_trasera' => 'GorraLlamasAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Beanie bordado crema',
                'descripcion' => 'Gorro tipo beanie (de punto ajustado o suelto) con detalle de bordado en color crema, que puede incluir logotipos, iniciales o diseños sencillos. En tono neutro y versátil, aporta calidez y estilo casual. Ideal para looks invernales cómodos y modernos, combinando sencillez con un toque elegante y personalizado.',
                'img_frontal' => 'GorroCremaFrontal.png',
                'img_trasera' => 'GorroCremaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra logo out of core',
                'descripcion' => 'Gorra de color negro con estampado o parche del logo "Out of Core" en tono rosa, que destaca con un estilo moderno y llamativo. Diseñada para fans de la marca, combina actitud streetwear con un toque de personalidad. Ideal para looks urbanos, informales o deportivos, aportando color y originalidad al outfit.',
                'img_frontal' => 'GorraCueroFrontal.png',
                'img_trasera' => 'GorraCueroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra better days bordada',
                'descripcion' => 'Gorra de color gris con detalle de bordado frontal que reza "Better Days" en estilo elegante o casual, dependiendo del tipo de letra. Aporta un mensaje positivo y sencillo, ideal para looks relajados y minimalistas. Perfecta para usar a diario, combinando comodidad, estilo y una vibra optimista.',
                'img_frontal' => 'GorraBetterDaysFrontal.png',
                'img_trasera' => 'GorraBetterDaysTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas sol polarizadas negras',
                'descripcion' => 'Gafas con lentes oscuros de color negro y tecnología polarizada, ideal para reducir reflejos y mejorar la visión bajo la luz solar intensa. Diseño clásico y versátil, perfecto para cualquier ocasión. Ofrecen protección UV y un estilo atemporal, combinando funcionalidad y elegancia en un formato sencillo y moderno.',
                'img_frontal' => 'GafasSolNegrasFrontal.png',
                'img_trasera' => 'GafasSolNegrasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra bordada roja',
                'descripcion' => 'Gorra con detalle de bordado en tono burdeos (rojo oscuro con matices profundos), que puede incluir logotipos, palabras o diseños decorativos. Este color aporta un toque elegante y sobrio al look. Ideal para estilos minimalistas, casuales o clásicos, combinando comodidad con un aire sofisticado y discreto.',
                'img_frontal' => 'GorraRojaFrontal.png',
                'img_trasera' => 'GorraRojaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas sol pasta transparente',
                'descripcion' => 'Gafas con montura fabricada en material plástico transparente o semi-transparente, que aporta un look discreto pero moderno. Los cristales suelen ser oscuros (grises, verdes o marrones) para ofrecer protección solar y contraste visual. Diseño versátil y minimalista, ideal para looks casuales, urbanos o fashion. Perfectas para quienes buscan comodidad, elegancia sencilla y un estilo atemporal.',
                'img_frontal' => 'GafasSolMarronFrontal.png',
                'img_trasera' => 'GafasSolMarronTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PIE -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Botín deportivo Avia',
                'descripcion' => 'Zapato tipo zapatilla botín para hombre. Logo en corte. Combinación de colores y materiales en corte. Cierre mediante cordones a tono. Suela a contraste. Tirador trasero para facilitar el calce.',
                'img_frontal' => 'zapatillas_blancas_frontal.png',
                'img_trasera' => 'zapatillas_blancas_trasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Chancla baño negras',
                'descripcion' => 'Zapato tipo chancla para hombre. Disponible en varios colores. Detalle tira posicionamiento dedo.',
                'img_frontal' => 'frontalChanclasNegras.png',
                'img_trasera' => 'traseraChanclasNegras.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapato náutico piel',
                'descripcion' => 'Zapato tipo náutico de vestir para hombre. Confeccionados con piel de serraje. Cierre mediante cordones. Pasadores metálicos. Suela a contraste.',
                'img_frontal' => 'frontalZapatoNautico.png',
                'img_trasera' => 'traseraZapatoNautico.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Deportivo boxing out of core',
                'descripcion' => 'Altura caña: 19 cm. Plantilla técnica extraible, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'botasRosasFrontal.png',
                'img_trasera' => 'botasRosasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Deportivo fútbol out of core',
                'descripcion' => 'Plantilla técnica extraible, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasDoradasFrontal.png',
                'img_trasera' => 'bambasDoradasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Deportivo out of core negro',
                'descripcion' => 'Plantilla técnica extraible, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasNegrasFrontal.png',
                'img_trasera' => 'bambasNegrasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapatilla skate multipiezas marrones',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasMarronesFrontal.png',
                'img_trasera' => 'bambasMarronesTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapatillas retro blancas',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de látex, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasBlancasNegrasFrontal.png',
                'img_trasera' => 'bambasBlancasNegrasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapatillas volumen skate blancas',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasBlancasFrontal.png',
                'img_trasera' => 'bambasBlancasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapatillas suela volumen grises',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'bambasGrisesFrontal.png',
                'img_trasera' => 'bambasGrisesTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Mocasín suela fina negros',
                'descripcion' => 'AIRFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'mocasinNegroFrontal.png',
                'img_trasera' => 'mocasinNegroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapato acordonado PIEL animal print',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'mocasinNegroFrontal.png',
                'img_trasera' => 'mocasinNegroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Botín cowboy negros',
                'descripcion' => 'STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'botasNegrasFrontal.png',
                'img_trasera' => 'botasNegrasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Sandalia tiras negras',
                'descripcion' => 'AIRFIT®. Plantilla técnica flexible de espuma compuesta de látex, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'sandaliasNegrasFrontal.png',
                'img_trasera' => 'sandaliasNegrasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Mocasín combinado rojo',
                'descripcion' => 'AIRFIT®. Plantilla técnica flexible de espuma compuesta de látex, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'mocasinRojoFrontal.png',
                'img_trasera' => 'mocasinRojoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Botín cowboy punta metalizada marron',
                'descripcion' => 'Altura tacón: 5.5 cm. STARFIT®. Plantilla técnica flexible de espuma compuesta de poliuretano, diseñada para ofrecer un mayor confort.',
                'img_frontal' => 'botaMarronFrontal.png',
                'img_trasera' => 'botaMarronTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
