<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrendaSeeder extends Seeder
{
    public function run()
    {
        DB::table('prendas')->insert([
            // TORSO -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Mickey Mouse Blanca',
                'descripcion' => 'Camiseta básica de algodón color blanco, perfecta para el día a día.',
                'img_frontal' => 'frontalBlancaMickey.png',
                'img_trasera' => 'traseraBlancaMikey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camisa azul clara con estampados',
                'descripcion' => 'Camisa de lino azul clara, ideal para ocasiones semi-formales.',
                'img_frontal' => 'frontalVanGogh.png',
                'img_trasera' => 'traseraVanGogh.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera PSG',
                'descripcion' => 'Sudadera casual gris de manga larga y cuello redondo. Cuenta con logo de Paris Saint-Germain engomado en la parte delantera y estampado en la parte trasera, con detalle de parche en el bajo y un suave cepillado interior. Tiene acabado de canalé en cuello, puños y bajo de la prenda. Es de corte holgado.',
                'img_frontal' => 'frontalSudaderaPSG.png',
                'img_trasera' => 'traseraSudaderaPSG.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera negra PONY',
                'descripcion' => 'Sudadera de felpa de manga larga y cuello redondo. Cuenta con detalle de estampado de Pony x Lefties en la parte delantera, detalle de parche en el bajo y estampado de texto en la espalda. Tiene acabado de canalé en cuello, bajo y puños.',
                'img_frontal' => 'frontalSudaderaPONY.png',
                'img_trasera' => 'traseraSudaderaPONY.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera estampada capucha',
                'descripcion' => 'Sudadera carne de manga larga y cuello capucha con acabados en canale. Es de corte relajado. Cuenta con estampado en la parte delantera y suave cepillado interior. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaEstampadaCapucha.png',
                'img_trasera' => 'traseraSudaderaEstampadaCapucha.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera verde QUEENS',
                'descripcion' => 'Sudadera de manga larga y cuello redondo con acabados en canalé. Cuenta con estampado frontal delantero. Es de corte relajado y está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaQUEENS.png',
                'img_trasera' => 'traseraSudaderaQUEENS.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Le Studio',
                'descripcion' => 'Sudadera elegante estampada de manga larga y cuello capucha con acabado de canalé en puños y bajo. Es de corte relajado. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaLeStudio.png',
                'img_trasera' => 'traseraSudaderaLeStudio.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Villa Club',
                'descripcion' => 'Sudadera elegante de manga larga y cuello polo con cierre frontal de botones a tono. Cuenta con distintos bordados en la parte delantera de la prenda. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaVillaClub.png',
                'img_trasera' => 'traseraSudaderaVillaClub.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera bordada roja',
                'descripcion' => 'Sudadera de manga larga y cuello redondo. Tiene acabado de canalé en el bajo, puños y cuello. Cuenta con bordado de texto delantero. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaClubMember.png',
                'img_trasera' => 'traseraSudaderaClubMember.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Sudadera Paris Saint-Germain Blanco',
                'descripcion' => 'Sudadera de manga larga y capucha con distintos estampados del equipo de fútbol Paris Saint-Germain, incluido uno en la capucha. Cuenta con detalle de parche en el brazo derecho. Tiene un suave cepillado interior. Es de corte ligeramente holgado.',
                'img_frontal' => 'frontalSudaderaPSGBlanco.png',
                'img_trasera' => 'traseraSudaderaPSGBlanco.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Camiseta Paris Saint-Germain Negra',
                'descripcion' => 'Camiseta de manga corta y cuello redondo con estampados del equipo de fútbol Paris Saint-Germain por toda la prenda. Es de corte recto.',
                'img_frontal' => 'frontalCamisetaPSGNegra.png',
                'img_trasera' => 'traseraCamisetaPSGNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'nombre' => 'Jersey punto cremallera',
                'descripcion' => 'Jersey de manga larga y cuello subido con cierre de cremallera metálica en el pecho. Es de corte recto y está confeccionado en tejido de punto.',
                'img_frontal' => 'frontaljerseyNegroCremallero.png',
                'img_trasera' => 'traserajerseyNegroCremallero.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // PIERNA -----------------------------------------------------------------------------------------------

            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans Comfort Skinny Premium',
                'descripcion' => 'Pantalón azul vaquero básico de cinco bolsillos con cierre de botón metálico y cremallera. Su corte comfort skinny es ajustado y de tiro medio pero resulta muy cómodo gracias a la elasticidad de su tejido. El tejido, su elasticidad reforzada y la atención a sus detalles de diseño hacen de este modelo nuestro vaquero premium.',
                'img_frontal' => 'frontaljeansAzulesSkinny.png',
                'img_trasera' => 'traserajeansAzulesSkinny.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans jogger rotos negros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotos.png',
                'img_trasera' => 'traserajeansJoggerRotos.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans jogger rotos vaqueros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotosVaqueros.png',
                'img_trasera' => 'traserajeansJoggerRotosVaqueros.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón chándal Paris Saint-Germain',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Tiene distintos estampados del equipo de fútbol Paris Saint-Germain. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche. Tiene un suave cepillado interior.',
                'img_frontal' => 'frontalChandalPSGGris.png',
                'img_trasera' => 'traseraChandalPSGGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón chándal interlock',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger y cordón de ajuste a contraste. Cuenta con dos bolsillos laterales y uno trasero. Es de corte ligeramente ajustado. Está confeccionado en tejido de felpa con paneles con textura.',
                'img_frontal' => 'frontalChandalInterlockGris.png',
                'img_trasera' => 'traseraChandalInterlockGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda Paris Saint-Germain negra',
                'descripcion' => 'Bermuda de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con estampados engomados del equipo de fútbol Paris Saint-Germain. Tiene dos bolsillos laterales y un bolsillo trasero con detalle de parche. Está confeccionada en un tejido de felpa interlock.',
                'img_frontal' => 'frontalCortoPSGNegro.png',
                'img_trasera' => 'traseraCortoPSGNegro.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda elástica deportiva',
                'descripcion' => 'Bermuda azul oscuro deportiva con bolsillos de tejido técnico y detalles reflectantes en la parte trasera. Tiene cintura elástica con lazada delantera. Cuenta con un bolsillo oculto con cremallera junto al bolsillo derecho.',
                'img_frontal' => 'frontalBermudaDeportivaAzul.png',
                'img_trasera' => 'traseraBermudaDeportivaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim relaxed',
                'descripcion' => 'Bermuda denim relaxed',
                'img_frontal' => 'frontalBermudaNegra.png',
                'img_trasera' => 'traseraBermudaNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda jogger estructura Azul',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche.',
                'img_frontal' => 'frontalBermudaAzul.png',
                'img_trasera' => 'traseraBermudaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda jogger estructura Verde',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'frontalBermudaVerde.png',
                'img_trasera' => 'traseraBermudaVerde.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Bermuda denim skater',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoCortoAzulFrontal.png',
                'img_trasera' => 'tejanoCortoAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans 90s straight negros',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoNegroFrontal.png',
                'img_trasera' => 'tejanoLargoNegrotrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy jacquard blancos',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoBlancoFrontal.png',
                'img_trasera' => 'tejanoLargoBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans super baggy azul fuerte',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulFuerteFrontal.png',
                'img_trasera' => 'tejanoLargoAzulFuerteTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón baggy técnico Verde',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalGrisVerdeFrontal.png',
                'img_trasera' => 'chandalGrisVerdeTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy azul',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulFrontal.png',
                'img_trasera' => 'tejanoLargoAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy print blanca y marron',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoBlancoMarronFrontal.png',
                'img_trasera' => 'tejanoLargoBlancoMarronTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans baggy jacquard azul claro',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoAzulEspecialFrontal.png',
                'img_trasera' => 'tejanoLargoAzulEspecialTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón técnico ribete sport',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalNegroFrontal.png',
                'img_trasera' => 'chandalNegroTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Pantalón Volkswagen jacquard',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'chandalVerdeBlancoFrontal.png',
                'img_trasera' => 'chandalVerdeBlancoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'nombre' => 'Jeans super baggy rotos',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'tejanoLargoGrisFrontal.png',
                'img_trasera' => 'tejanoLargoGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // CABEZA -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra Dragon Ball ©Bird Studio',
                'descripcion' => 'Gorra de visera curva con estampados de Dragon Ball ©Bird Studio en la parte delantera. Cuenta con rejilla en la parte trasera a contraste y cinta de ajuste adherente en la parte trasera.',
                'img_frontal' => 'frontalGorraDB.png',
                'img_trasera' => 'traseraGorraDB.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gorra Brooklyn Nets NBA Blanca y Negra',
                'descripcion' => 'Gorra de visera curva con cinta adherente en parte trasera para mejor ajuste. Cuenta con estampado a contraste de Brooklyn Nets NBA en parte delantera.',
                'img_frontal' => 'frontalGorraNBA.png',
                'img_trasera' => 'traseraGorraNBA.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas básicas efecto carey',
                'descripcion' => 'Gafas de sol de cristal redondo y montura de pasta acabada en efecto carey.',
                'img_frontal' => 'frontalGafasCarey.png',
                'img_trasera' => 'traseraGafasCarey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1,
                'nombre' => 'Gafas rectangulares',
                'descripcion' => 'Gafas de sol de cristal rectangular con montura de pasta semitransparente.',
                'img_frontal' => 'frontalGafasRectangulares.png',
                'img_trasera' => 'traseraGafasRectangulares.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PIE -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Botín deportivo Avia',
                'descripcion' => 'Zapato tipo zapatilla botín para hombre. Logo en corte. Combinación de colores y materiales en corte. Cierre mediante cordones a tono. Suela a contraste. Tirador trasero para facilitar el calce.',
                'img_frontal' => 'zapatillas_blancas_frontal.png',
                'img_trasera' => 'zapatillas_blancas_trasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Chancla baño negras',
                'descripcion' => 'Zapato tipo chancla para hombre. Disponible en varios colores. Detalle tira posicionamiento dedo.',
                'img_frontal' => 'frontalChanclasNegras.png',
                'img_trasera' => 'traseraChanclasNegras.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'nombre' => 'Zapato náutico piel',
                'descripcion' => 'Zapato tipo náutico de vestir para hombre. Confeccionados con piel de serraje. Cierre mediante cordones. Pasadores metálicos. Suela a contraste.',
                'img_frontal' => 'frontalZapatoNautico.png',
                'img_trasera' => 'traseraZapatoNautico.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
