<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrendaColoresSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prenda_colores')->insert([
            ['id_prenda' => 1, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 2, 'id_color' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 3, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 3, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 4, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 5, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 6, 'id_color' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 7, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 8, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 9, 'id_color' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 10, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 11, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 12, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 13, 'id_color' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 14, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 14, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 15, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 16, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 16, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 17, 'id_color' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 18, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 18, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 19, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 19, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 19, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 20, 'id_color' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 20, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 21, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 21, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 22, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 23, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 24, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 25, 'id_color' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 25, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 26, 'id_color' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 26, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 27, 'id_color' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 27, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 28, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 28, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 28, 'id_color' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 29, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 29, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 30, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 30, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 31, 'id_color' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 32, 'id_color' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 32, 'id_color' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 33, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 34, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 35, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 36, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 37, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 38, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 39, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 40, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 41, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 42, 'id_color' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 43, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 44, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 45, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 46, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 47, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 47, 'id_color' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 48, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 49, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 49, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 50, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 50, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 101, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 100, 'id_color' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 99, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 98, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 97, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 97, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 97, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 96, 'id_color' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 95, 'id_color' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 94, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 93, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 92, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 91, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 90, 'id_color' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 89, 'id_color' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 88, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 87, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 86, 'id_color' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 85, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 84, 'id_color' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 83, 'id_color' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 82, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 81, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 80, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 79, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 78, 'id_color' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 77, 'id_color' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 76, 'id_color' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 75, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 74, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 73, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 72, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 71, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 70, 'id_color' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 69, 'id_color' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 68, 'id_color' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 67, 'id_color' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 66, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 65, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 64, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 63, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 63, 'id_color' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 62, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 61, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 60, 'id_color' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 59, 'id_color' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 59, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 58, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 58, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 57, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 57, 'id_color' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 56, 'id_color' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 55, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 54, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 53, 'id_color' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 53, 'id_color' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 52, 'id_color' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 52, 'id_color' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['id_prenda' => 51, 'id_color' => 30, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
