<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrendaSeeder extends Seeder
{
    public function run()
    {
        DB::table('prendas')->insert([
            // TORSO -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 2, 
                'precio' => 29.99,
                'nombre' => 'Camiseta Mickey Mouse Blanca',
                'descripcion' => 'Camiseta básica de algodón color blanco, perfecta para el día a día.',
                'img_frontal' => 'frontalBlancaMickey.png',
                'img_trasera' => 'traseraBlancaMikey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 49.99,
                'nombre' => 'Camisa azul clara con estampados',
                'descripcion' => 'Camisa de lino azul clara, ideal para ocasiones semi-formales.',
                'img_frontal' => 'frontalVanGogh.png',
                'img_trasera' => 'traseraVanGogh.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'precio' => 9.99,
                'nombre' => 'Sudadera PSG',
                'descripcion' => 'Sudadera casual gris de manga larga y cuello redondo. Cuenta con logo de Paris Saint-Germain engomado en la parte delantera y estampado en la parte trasera, con detalle de parche en el bajo y un suave cepillado interior. Tiene acabado de canalé en cuello, puños y bajo de la prenda. Es de corte holgado.',
                'img_frontal' => 'frontalSudaderaPSG.png',
                'img_trasera' => 'traseraSudaderaPSG.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'precio' => 19.99,
                'nombre' => 'Sudadera negra PONY',
                'descripcion' => 'Sudadera de felpa de manga larga y cuello redondo. Cuenta con detalle de estampado de Pony x Lefties en la parte delantera, detalle de parche en el bajo y estampado de texto en la espalda. Tiene acabado de canalé en cuello, bajo y puños.',
                'img_frontal' => 'frontalSudaderaPONY.png',
                'img_trasera' => 'traseraSudaderaPONY.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'precio' => 12.99,
                'nombre' => 'Sudadera estampada capucha',
                'descripcion' => 'Sudadera carne de manga larga y cuello capucha con acabados en canale. Es de corte relajado. Cuenta con estampado en la parte delantera y suave cepillado interior. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaEstampadaCapucha.png',
                'img_trasera' => 'traseraSudaderaEstampadaCapucha.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'precio' => 9.99,
                'nombre' => 'Sudadera verde QUEENS',
                'descripcion' => 'Sudadera de manga larga y cuello redondo con acabados en canalé. Cuenta con estampado frontal delantero. Es de corte relajado y está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaQUEENS.png',
                'img_trasera' => 'traseraSudaderaQUEENS.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2,
                'precio' => 15.99,
                'nombre' => 'Sudadera Le Studio',
                'descripcion' => 'Sudadera elegante estampada de manga larga y cuello capucha con acabado de canalé en puños y bajo. Es de corte relajado. Está confeccionada en tejido de felpa.',
                'img_frontal' => 'frontalSudaderaLeStudio.png',
                'img_trasera' => 'traseraSudaderaLeStudio.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 19.99,
                'nombre' => 'Sudadera Villa Club',
                'descripcion' => 'Sudadera elegante de manga larga y cuello polo con cierre frontal de botones a tono. Cuenta con distintos bordados en la parte delantera de la prenda. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaVillaClub.png',
                'img_trasera' => 'traseraSudaderaVillaClub.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 17.99,
                'nombre' => 'Sudadera bordada roja',
                'descripcion' => 'Sudadera de manga larga y cuello redondo. Tiene acabado de canalé en el bajo, puños y cuello. Cuenta con bordado de texto delantero. Es de corte ligeramente holgado y está confeccionado en un tejido de algodón elástico.',
                'img_frontal' => 'frontalSudaderaClubMember.png',
                'img_trasera' => 'traseraSudaderaClubMember.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 22.99,
                'nombre' => 'Sudadera Paris Saint-Germain Blanco',
                'descripcion' => 'Sudadera de manga larga y capucha con distintos estampados del equipo de fútbol Paris Saint-Germain, incluido uno en la capucha. Cuenta con detalle de parche en el brazo derecho. Tiene un suave cepillado interior. Es de corte ligeramente holgado.',
                'img_frontal' => 'frontalSudaderaPSGBlanco.png',
                'img_trasera' => 'traseraSudaderaPSGBlanco.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 15.99,
                'nombre' => 'Camiseta Paris Saint-Germain Negra',
                'descripcion' => 'Camiseta de manga corta y cuello redondo con estampados del equipo de fútbol Paris Saint-Germain por toda la prenda. Es de corte recto.',
                'img_frontal' => 'frontalCamisetaPSGNegra.png',
                'img_trasera' => 'traseraCamisetaPSGNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 29.99,
                'nombre' => 'Jersey punto cremallera',
                'descripcion' => 'Jersey de manga larga y cuello subido con cierre de cremallera metálica en el pecho. Es de corte recto y está confeccionado en tejido de punto.',
                'img_frontal' => 'frontaljerseyNegroCremallero.png',
                'img_trasera' => 'traserajerseyNegroCremallero.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 15.99,
                'nombre' => 'Camiseta manga corta print rosa',
                'descripcion' => 'Camiseta de rayas de algodón color rosa con dibujo en el pecho, perfecta para el día a día.',
                'img_frontal' => 'CamisetaMangaCortaPrintRosaFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaPrintRosaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 25.99,
                'nombre' => 'Camisa manga corta boxy',
                'descripcion' => 'Camisa manga corta boxy fit de rayas color azul de algodón, perfecta para el verano.',
                'img_frontal' => 'CamisaMangaCortaBoxyRayasFrontal.png',
                'img_trasera' => 'CamisaMangaCortaBoxyRayasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 25.99,
                'nombre' => 'Camisa manga corta boxy bordado',
                'descripcion' => 'Camisa manga corta boxy fit color azul marino de algodón con bordado en la parte trasera, perfecta para el verano.',
                'img_frontal' => 'CamisaMangaCortaBoxyBordadaFrontal.png',
                'img_trasera' => 'CamisaMangaCortaBoxyBordadaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 25.99,
                'nombre' => 'Polo rayas',
                'descripcion' => 'Polo manga corta color azul con rayas negras y botones en el pecho, para ir formal pero cómodo.',
                'img_frontal' => 'PoloMangaCortaRayasFrontal.png',
                'img_trasera' => 'PoloMangaCortaRayasTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 29.99,
                'nombre' => 'Camisa manga corta rota',
                'descripcion' => 'Camisa de color caqui (tono tierra suave) con mangas cortas y detalles deliberados de rotos o desgastes, dando un estilo casual y ligeramente desgastado. Ideal para looks informales con toque moderno.',
                'img_frontal' => 'CamisaMangaCortaRotaFrontal.png',
                'img_trasera' => 'CamisaMangaCortaRotaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 26.59,
                'nombre' => 'Camisa manga corta textura print',
                'descripcion' => 'Camisa con mangas cortas en tono arena (beige suave), con diseño de textura o estampado que imita la apariencia del suelo desértico o arenoso. Brinda un estilo natural, fresco y versátil, ideal para ocasiones casuales o informales.',
                'img_frontal' => 'CamisaMangaCortaTexturaPrintFrontal.png',
                'img_trasera' => 'CamisaMangaCortaTexturaPrintTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 27.99,
                'nombre' => 'Cazadora técnica sport',
                'descripcion' => 'Chaqueta deportiva de corte moderno y funcional, en tono azul claro. Diseñada con materiales resistentes y cómodos, ideal para actividades al aire libre o para un estilo casual pero activo.',
                'img_frontal' => 'CazadoraTecnicaSportAzulFrontal.png',
                'img_trasera' => 'CazadoraTecnicaSportAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 12.99,
                'nombre' => 'Camiseta manga corta rib contraste',
                'descripcion' => 'Camiseta de tiras anchas (rib) en colores blanco y rojo, con diseño de contraste entre ambos tonos. De manga corta y corte ajustado o entallado, ideal para un look retro, deportivo o casual con estilo definido.',
                'img_frontal' => 'CamisetaMangaCortaRibRojaFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaRibRojaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 39.99,
                'nombre' => 'Cazadora rayas bordado',
                'descripcion' => 'Chaqueta con diseño de rayas en blanco y negro, decorada con detalles de bordado. Combina un estilo clásico y moderno, aportando un toque elegante y original. Ideal para looks casuales con personalidad.',
                'img_frontal' => 'CazadoraRayasBordadaFrontal.png',
                'img_trasera' => 'CazadoraRayasBordadaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 35.99,
                'nombre' => 'Cazadora denim trucker',
                'descripcion' => 'Chaqueta tipo trucker fabricada en denim de color azul marino. Cuenta con bolsillos frontales característicos y cierre mediante botones, ofreciendo un estilo clásico y versátil. Ideal para looks casuales y combinaciones sencillas pero con actitud.',
                'img_frontal' => 'CazadoraDenimTruckerFrontal.png',
                'img_trasera' => 'CazadoraDenimTruckerTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 35.99,
                'nombre' => 'Chaqueta Everlast cropped boxeo',
                'descripcion' => 'Chaqueta corta (cropped) de estilo deportivo, inspirada en la vestimenta de boxeo, de color gris y cierre con cremallera. Marca Everlast, conocida por su calidad en prendas de deporte. Ideal para looks urbanos, cómodos y con toque atlético.',
                'img_frontal' => 'ChaquetaEverlastCroppedBoxeoFrontal.png',
                'img_trasera' => 'ChaquetaEverlastCroppedBoxeoTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 7.99,
                'nombre' => 'Camiseta manga corta básica',
                'descripcion' => 'Prenda esencial de color negro, con mangas cortas y corte ajustado o regular. Versátil y sencilla, ideal para combinar en cualquier estilo, desde casual hasta más estilizado. Perfecta para usar sola o como base en capas.',
                'img_frontal' => 'CamisetaCortaBásicaNegraFrontal.png',
                'img_trasera' => 'CamisetaCortaBásicaNegraTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 22.99,
                'nombre' => 'Camiseta manga corta mesh sport print',
                'descripcion' => 'Camiseta deportiva de color azul, con diseño en malla (mesh) para mayor transpirabilidad. Cuenta con un estampado frontal minimalista y en la parte trasera presenta números y letras blancos, típicos de uniformes atléticos o estilo retro deportivo. Ideal para looks activos, informales o con inspiración sport.',
                'img_frontal' => 'CamisetaMangaCortaMeshSportFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaMeshSportTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 29.99,
                'nombre' => 'Camiseta Nascar manga larga print',
                'descripcion' => 'Camiseta de manga larga con diseño inspirado en la temática NASCAR, en tono rosa. Cuenta con estampados característicos como logotipos, banderas o gráficos relacionados con el automovilismo. Ideal para quienes buscan un estilo casual con toque deportivo y colorido.',
                'img_frontal' => 'CamisetaNascarMangaLargaFrontal.png',
                'img_trasera' => 'CamisetaNascarMangaLargaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 25.99,
                'nombre' => 'Polo manga corta sport mesh',
                'descripcion' => 'Polo de estilo deportivo confeccionado en tejido mesh para mayor transpiración. Presenta un diseño en blanco roto como color principal, con detalles en azul en el cuello y en los bordes de las mangas. Ideal para looks informales o deportivos, combinando comodidad, frescura y un toque moderno.',
                'img_frontal' => 'PoloMangaCortaMeshFrontal.png',
                'img_trasera' => 'PoloMangaCortaMeshTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 22.99,
                'nombre' => 'Polo manga corta varsity parche',
                'descripcion' => 'Polo de corte deportivo inspirado en el estilo varsity (universitario), con manga corta y diseño color block. Presenta un parche rojo en el pecho, combinado con detalles de rayas negras y blancas en el cuerpo o mangas. Ideal para looks dinámicos y juveniles, aportando un toque retro y atlético al outfit.',
                'img_frontal' => 'PoloMangaCortaVarsityFrontal.png',
                'img_trasera' => 'PoloMangaCortaVarsityTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 25.99,
                'nombre' => 'Camiseta Everlast manga corta mesh',
                'descripcion' => 'Camiseta de la marca Everlast, con mangas cortas y confeccionada en tejido mesh transpirable. De color azul marino como base, incorpora rayas horizontales blancas que le dan un estilo deportivo y clásico. Ideal para looks activos o casuales, combinando comodidad, frescura y un toque atlético.',
                'img_frontal' => 'CamisetaEverlastMangaCortaFrontal.png',
                'img_trasera' => 'CamisetaEverlastMangaCortaTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 12.99,
                'nombre' => 'Camiseta manga corta rib contraste',
                'descripcion' => 'Camiseta de corte ajustado confeccionada en tejido rib (elástico y entrelazado), en combinación de tonos: azul claro y azul marino. Su diseño de contraste aporta dinamismo y estilo, ideal para looks informales o deportivos, combinando elegancia casual y comodidad.',
                'img_frontal' => 'CamisetaMangaCortaRibAzulFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaRibAzulTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 12.99,
                'nombre' => 'Camiseta manga corta print',
                'descripcion' => 'Camiseta de manga corta en tono suave tipo arena (beige claro), con estampado en contraste que puede incluir motivos geométricos, tribales o abstractos. Aporta un estilo fresco, natural y versátil, ideal para looks casuales o inspirados en tendencias bohemias o playeras.',
                'img_frontal' => 'CamisetaMangaCortaPrintFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaPrintTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 2, 
                'precio' => 12.99,
                'nombre' => 'Camiseta manga corta contraste print gris',
                'descripcion' => 'Camiseta de manga corta con diseño de estampado en tonos de gris, combinando diferentes intensidades o texturas del color para crear un efecto de contraste. Corte moderno y versátil, ideal para looks urbanos, informales o minimalistas, aportando estilo sencillo pero elegante.',
                'img_frontal' => 'CamisetaMangaCortaContrasteGrisFrontal.png',
                'img_trasera' => 'CamisetaMangaCortaContrasteGrisTrasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            
            // PIERNA -----------------------------------------------------------------------------------------------

            [
                'id_tipoPrenda' => 3,
                'precio' => 18.99,
                'nombre' => 'Jeans Comfort Skinny Premium',
                'descripcion' => 'Pantalón azul vaquero básico de cinco bolsillos con cierre de botón metálico y cremallera. Su corte comfort skinny es ajustado y de tiro medio pero resulta muy cómodo gracias a la elasticidad de su tejido. El tejido, su elasticidad reforzada y la atención a sus detalles de diseño hacen de este modelo nuestro vaquero premium.',
                'img_frontal' => 'frontaljeansAzulesSkinny.png',
                'img_trasera' => 'traserajeansAzulesSkinny.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 18.19,
                'nombre' => 'Jeans jogger rotos negros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotos.png',
                'img_trasera' => 'traserajeansJoggerRotos.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 18.19,
                'nombre' => 'Jeans jogger rotos vaqueros',
                'descripcion' => 'Pantalón vaquero tipo jogger básico roto. Cuenta con cordón de ajuste en la cintura. Tiene dos bolsillos laterales y dos traseros. Está confeccionado en tejido de algodón elástico.',
                'img_frontal' => 'frontaljeansJoggerRotosVaqueros.png',
                'img_trasera' => 'traserajeansJoggerRotosVaqueros.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 22.99,
                'nombre' => 'Pantalón chándal Paris Saint-Germain',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Tiene distintos estampados del equipo de fútbol Paris Saint-Germain. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche. Tiene un suave cepillado interior.',
                'img_frontal' => 'frontalChandalPSGGris.png',
                'img_trasera' => 'traseraChandalPSGGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 17.99,
                'nombre' => 'Pantalón chándal interlock',
                'descripcion' => 'Pantalón de chándal de cintura elástica tipo jogger y cordón de ajuste a contraste. Cuenta con dos bolsillos laterales y uno trasero. Es de corte ligeramente ajustado. Está confeccionado en tejido de felpa con paneles con textura.',
                'img_frontal' => 'frontalChandalInterlockGris.png',
                'img_trasera' => 'traseraChandalInterlockGris.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 17.99,
                'nombre' => 'Bermuda Paris Saint-Germain negra',
                'descripcion' => 'Bermuda de chándal de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con estampados engomados del equipo de fútbol Paris Saint-Germain. Tiene dos bolsillos laterales y un bolsillo trasero con detalle de parche. Está confeccionada en un tejido de felpa interlock.',
                'img_frontal' => 'frontalCortoPSGNegro.png',
                'img_trasera' => 'traseraCortoPSGNegro.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 12.99,
                'nombre' => 'Bermuda elástica deportiva',
                'descripcion' => 'Bermuda azul oscuro deportiva con bolsillos de tejido técnico y detalles reflectantes en la parte trasera. Tiene cintura elástica con lazada delantera. Cuenta con un bolsillo oculto con cremallera junto al bolsillo derecho.',
                'img_frontal' => 'frontalBermudaDeportivaAzul.png',
                'img_trasera' => 'traseraBermudaDeportivaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 17.99,
                'nombre' => 'Bermuda denim relaxed',
                'descripcion' => 'Bermuda denim relaxed',
                'img_frontal' => 'frontalBermudaNegra.png',
                'img_trasera' => 'traseraBermudaNegra.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 11.99,
                'nombre' => 'Bermuda jogger estructura Azul',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche.',
                'img_frontal' => 'frontalBermudaAzul.png',
                'img_trasera' => 'traseraBermudaAzul.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 3,
                'precio' => 11.99,
                'nombre' => 'Bermuda jogger estructura Verde',
                'descripcion' => 'Bermuda de cintura elástica tipo jogger con cordón de ajuste a tono. Cuenta con dos bolsillos laterales y uno trasero con detalle de parche',
                'img_frontal' => 'frontalBermudaVerde.png',
                'img_trasera' => 'traseraBermudaVerde.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


           // CABEZA -----------------------------------------------------------------------------------------------
            [
                'id_tipoPrenda' => 1, 
                'precio' => 7.99,
                'nombre' => 'Gorra Dragon Ball ©Bird Studio',
                'descripcion' => 'Gorra de visera curva con estampados de Dragon Ball ©Bird Studio en la parte delantera. Cuenta con rejilla en la parte trasera a contraste y cinta de ajuste adherente en la parte trasera.',
                'img_frontal' => 'frontalGorraDB.png',
                'img_trasera' => 'traseraGorraDB.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1, 
                'precio' => 12.99,
                'nombre' => 'Gorra Brooklyn Nets NBA Blanca y Negra',
                'descripcion' => 'Gorra de visera curva con cinta adherente en parte trasera para mejor ajuste. Cuenta con estampado a contraste de Brooklyn Nets NBA en parte delantera.',
                'img_frontal' => 'frontalGorraNBA.png',
                'img_trasera' => 'traseraGorraNBA.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1, 
                'precio' => 1.99,
                'nombre' => 'Gafas básicas efecto carey',
                'descripcion' => 'Gafas de sol de cristal redondo y montura de pasta acabada en efecto carey.',
                'img_frontal' => 'frontalGafasCarey.png',
                'img_trasera' => 'traseraGafasCarey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 1, 
                'precio' => 5.99,
                'nombre' => 'Gafas rectangulares',
                'descripcion' => 'Gafas de sol de cristal rectangular con montura de pasta semitransparente.',
                'img_frontal' => 'frontalGafasRectangulares.png',
                'img_trasera' => 'traseraGafasRectangulares.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

           // PIE -----------------------------------------------------------------------------------------------
           [
                'id_tipoPrenda' => 4,
                'precio' => 39.99,
                'nombre' => 'Botín deportivo Avia',
                'descripcion' => 'Zapato tipo zapatilla botín para hombre. Logo en corte. Combinación de colores y materiales en corte. Cierre mediante cordones a tono. Suela a contraste. Tirador trasero para facilitar el calce.',
                'img_frontal' => 'zapatillas_blancas_frontal.png',
                'img_trasera' => 'zapatillas_blancas_trasera.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'precio' => 2.99,
                'nombre' => 'Chancla baño negras',
                'descripcion' => 'Zapato tipo chancla para hombre. Disponible en varios colores. Detalle tira posicionamiento dedo.',
                'img_frontal' => 'frontalChanclasNegras.png',
                'img_trasera' => 'traseraChanclasNegras.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_tipoPrenda' => 4,
                'precio' => 35.99,
                'nombre' => 'Zapato náutico piel',
                'descripcion' => 'Zapato tipo náutico de vestir para hombre. Confeccionados con piel de serraje. Cierre mediante cordones. Pasadores metálicos. Suela a contraste.',
                'img_frontal' => 'frontalZapatoNautico.png',
                'img_trasera' => 'traseraZapatoNautico.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
