<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuariosSeeder extends Seeder
{
    /**
     * Ejecutar la siembra de la base de datos.
     *
     * @return void
     */
    public function run()
    {
        DB::table('usuarios')->insert([
            [
                'nombre'         => 'Admin Principal',
                'email'          => 'admin@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 1,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Ejemplo',
                'email'          => 'cliente@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Empresa Ejemplo',
                'email'          => 'empresa@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 3,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Gestor Ejemplo',
                'email'          => 'gestor@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 4,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Programador Ejemplo',
                'email'          => 'programador@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 5,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'AdrianV',
                'email'          => 'adrian@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Orii',
                'email'          => 'oriol@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Eric Alca',
                'email'          => 'eric@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Daniel B',
                'email'          => 'daniel@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Christiann',
                'email'          => 'christian@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'JuanCa',
                'email'          => 'juanCarlos@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Alexito',
                'email'          => 'alex@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'David Álvarez',
                'email'          => 'david@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Marc DobleM',
                'email'          => 'marc@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Sergiii',
                'email'          => 'sergi@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'David H',
                'email'          => 'hompanera@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Fatima',
                'email'          => 'fatima@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Alberto De Santos',
                'email'          => 'alberto@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Agnes User',
                'email'          => 'agnes@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
