<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuariosSeeder extends Seeder
{
    /**
     * Ejecutar la siembra de la base de datos.
     *
     * @return void
     */
    public function run()
    {
        DB::table('usuarios')->insert([
            [
                'nombre'         => 'Admin Principal',
                'email'          => 'admin@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 1,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Ejemplo',
                'email'          => 'cliente@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'cliente2@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'adrian@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'oriol@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'eric@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'daniel@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'christian@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'juanCarlos@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'alex@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'david@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'marc@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'sergi@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'hompanera@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'fatima@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'alberto@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'nombre'         => 'Cliente Secundario',
                'email'          => 'agnes@pompitawear.com',
                'password'       => Hash::make('qweQWE123'),
                'id_rol'         => 2,
                'foto_perfil'    => null,
                'estado'         => 'activo',
                'is_private'     => false,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
